"""Reset automatico com datetimes corretos

Revision ID: 739cabcb03a0
Revises: 
Create Date: 2025-06-23 10:50:36.230810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739cabcb03a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadastros_globais_encerrados', sa.Boolean(), nullable=True),
    sa.Column('num_quadras_fut_masc', sa.Integer(), nullable=True),
    sa.Column('num_quadras_fut_fem', sa.Integer(), nullable=True),
    sa.Column('num_quadras_volei_misto', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracao'))
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('modalidade', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grupo'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=150), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_igreja', sa.String(length=150), nullable=False),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('regiao', sa.String(length=100), nullable=True),
    sa.Column('nome_base', sa.String(length=100), nullable=True),
    sa.Column('modalidade', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('lider_id', sa.Integer(), nullable=False),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.Column('link_pagamento', sa.String(length=200), nullable=True),
    sa.Column('pagou', sa.Boolean(), nullable=True),
    sa.Column('comprovante_pagamento', sa.String(length=255), nullable=True),
    sa.Column('diretor_jovem', sa.String(length=150), nullable=True),
    sa.Column('cadastros_encerrados', sa.Boolean(), nullable=True),
    sa.Column('chaveamento_json', sa.Text(), nullable=True),
    sa.Column('limite_nao_adv_fut_masc', sa.Integer(), nullable=True),
    sa.Column('limite_nao_adv_fut_fem', sa.Integer(), nullable=True),
    sa.Column('limite_nao_adv_volei_misto', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], name=op.f('fk_time_grupo_id_grupo')),
    sa.ForeignKeyConstraint(['lider_id'], ['user.id'], name=op.f('fk_time_lider_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time')),
    sa.UniqueConstraint('token', name=op.f('uq_time_token'))
    )
    op.create_table('classificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogos_disputados', sa.Integer(), nullable=True),
    sa.Column('vitorias', sa.Integer(), nullable=True),
    sa.Column('empates', sa.Integer(), nullable=True),
    sa.Column('derrotas', sa.Integer(), nullable=True),
    sa.Column('gols_pro', sa.Integer(), nullable=True),
    sa.Column('gols_contra', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], name=op.f('fk_classificacao_grupo_id_grupo')),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], name=op.f('fk_classificacao_time_id_time')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classificacao'))
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.String(length=50), nullable=False),
    sa.Column('fase', sa.String(length=100), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('finalizado', sa.Boolean(), nullable=False),
    sa.Column('ordem_na_fase', sa.Integer(), nullable=True),
    sa.Column('time_a_id', sa.Integer(), nullable=True),
    sa.Column('time_b_id', sa.Integer(), nullable=True),
    sa.Column('vencedor_id', sa.Integer(), nullable=True),
    sa.Column('gols_time_a', sa.Integer(), nullable=True),
    sa.Column('gols_time_b', sa.Integer(), nullable=True),
    sa.Column('sets_vencidos_a', sa.Integer(), nullable=True),
    sa.Column('sets_vencidos_b', sa.Integer(), nullable=True),
    sa.Column('pontos_sets', sa.String(length=200), nullable=True),
    sa.Column('proximo_jogo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proximo_jogo_id'], ['game.id'], name=op.f('fk_game_proximo_jogo_id_game')),
    sa.ForeignKeyConstraint(['time_a_id'], ['time.id'], name=op.f('fk_game_time_a_id_time')),
    sa.ForeignKeyConstraint(['time_b_id'], ['time.id'], name=op.f('fk_game_time_b_id_time')),
    sa.ForeignKeyConstraint(['vencedor_id'], ['time.id'], name=op.f('fk_game_vencedor_id_time')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game'))
    )
    op.create_table('jogador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('is_adventista', sa.Boolean(), nullable=True),
    sa.Column('foto_identidade', sa.String(length=255), nullable=True),
    sa.Column('is_capitao', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], name=op.f('fk_jogador_time_id_time')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jogador'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogador')
    op.drop_table('game')
    op.drop_table('classificacao')
    op.drop_table('time')
    op.drop_table('user')
    op.drop_table('grupo')
    op.drop_table('configuracao')
    # ### end Alembic commands ###
