"""Adicionar colunas de limite de nao adventistas

Revision ID: f73e7d12c788
Revises: ed21d0462702
Create Date: 2025-07-07 12:29:11.762291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73e7d12c788'
down_revision = 'ed21d0462702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limite_nao_adv_fut_masc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limite_nao_adv_fut_fem', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('limite_nao_adv_volei_misto', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.drop_column('limite_nao_adv_volei_misto')
        batch_op.drop_column('limite_nao_adv_fut_fem')
        batch_op.drop_column('limite_nao_adv_fut_masc')

    # ### end Alembic commands ###
